version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo-clean-arch
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: clean-arch-node

volumes:
  mongo_data: